workspaces:

  # Misc development projects:
  - name: twsm
    root: ~/Projects/twsm
  - name: object-graph-explorer
    root: ~/Projects/Java/object-graph-explorer
  - name: fir-box
    root: ~/Projects/SysAdmin/fir-box
  - name: Forest
    root: ~/Forest

  # @PaniniJ
  - name: at-paninij
    root: ~/Projects/Panini/at-paninij
  - name: at-paninij-benchmarks
    root: ~/Projects/Panini/at-paninij-benchmarks
  - name: at-paninij-examples
    root: ~/Projects/Panini/at-paninij-example

  # Java tooling experiments:
  - name: javac-ast-experiments
    root: ~/Projects/Java/javac-ast-experiments
  - name: dataflow-framework-examples
    root: ~/Projects/Java/dataflow-framework-examples

  # Research projects
  - name: hybrid-ownership-transfer
    root: ~/Research/SoftDesign/Pubs/hybrid-ownership-transfer
  - name: java-ownership-transfer
    root: ~/Research/SoftDesign/RFCs/java-ownership-transfer

  # Forest research topics:
  - name: ProgAnalysis
    root: ~/Forest/Programming Languages/Program Analysis
  - name: Java/ProgAnalysis
    root: ~/Forest/Programming Languages/Languages/Java/Program Analysis
  - name: Ownership
    root: ~/Forest/Programming Languages/Concepts/Ownership
  - name: Modularity
    root: ~/Forest/Programming Languages/Concepts/Modularity

  # Languages:
  - name: cpp-the-core-language
    root: ~/Projects/Learn/cpp-the-core-language
  - name: C++
    root: ~/Forest/Programming Languages/Languages/C++
  - name: Rust
    root: ~/Forest/Programming Languages/Languages/Rust

  # Java tool sources:
  - name: ductilej
    root: ~/Software/Java/ductilej
  - name: java-oo
    root: ~/Software/Java/java-oo
  - name: lombok
    root: ~/Software/Java/lombok
  - name: openjdk/jdk
    root: ~/Software/Java/openjdk/jdk8u/jdk
  - name: openjdk/langtools
    root: ~/Software/Java/openjdk/jdk8u/langtools
