workspaces:

  # Misc development projects:
  - name: twsm
    root: ~/Projects/twsm
  - name: object-graph-explorer
    root: ~/Projects/Java/object-graph-explorer
  - name: fir-box
    root: ~/Projects/SysAdmin/fir-box

  # @PaniniJ
  - name: at-paninij
    root: ~/Projects/Panini/at-paninij
  - name: at-paninij-benchmarks
    root: ~/Projects/Panini/at-paninij-benchmarks
  - name: at-paninij-examples
    root: ~/Projects/Panini/at-paninij-example

  # Java tooling experiments:
  - name: javac-ast-experiments
    root: ~/Projects/Java/javac-ast-experiments
  - name: dataflow-framework-examples
    root: ~/Projects/Java/dataflow-framework-examples

  # Language study projects
  - name: cpp-the-core-language
    root: ~/Projects/Learn/cpp-the-core-language

  # Research projects
  - name: hybrid-ownership-transfer
    root: ~/Research/SoftDesign/Pubs/hybrid-ownership-transfer
  - name: java-ownership-transfer
    root: ~/Research/SoftDesign/RFCs/java-ownership-transfer

  # Forest research topics:
  - name: Forest/ProgAnalysis
    root: ~/Forest/Programming Languages/Program Analysis
  - name: Forest/Java/ProgAnalysis
    root: ~/Forest/Programming Languages/Languages/Java/Program Analysis
  - name: Forest/Ownership
    root: ~/Forest/Programming Languages/Concepts/Ownership
  - name: Forest/Modularity
    root: ~/Forest/Programming Languages/Concepts/Modularity

  # Forest Languages:
  - name: Forest/C++
    root: ~/Forest/Programming Languages/Languages/C++
  - name: Forest/Rust
    root: ~/Forest/Programming Languages/Languages/Rust

  # Java tool sources:
  - name: Sources/ductilej
    root: ~/Software/Java/ductilej
  - name: Sources/java-oo
    root: ~/Software/Java/java-oo
  - name: Sources/lombok
    root: ~/Software/Java/lombok
  - name: Sources/openjdk/jdk
    root: ~/Software/Java/openjdk/jdk8u/jdk
  - name: Sources/openjdk/langtools
    root: ~/Software/Java/openjdk/jdk8u/langtools
